// Generates the root styles.css (the artifact Obsidian loads) from:
//   1. src/styles.css — hand-maintained plugin styles, and
//   2. @diagrammo/dgmo/block.css — the canonical embed-block chrome (BL-114),
//      with its dark-mode selector rewritten for Obsidian.
//
// dgmo's block.css keys dark mode on `[data-theme="dark"]`; Obsidian signals
// dark mode with `body.theme-dark`. This is the sanctioned adapter-level
// selector rewrite — same pattern as nextra-dgmo/fumadocs-dgmo's
// build-css.mjs (their hosts key on `html.dark`).

import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(import.meta.url);

const plugin = readFileSync(join(root, 'src', 'styles.css'), 'utf8');
const block = readFileSync(
  require.resolve('@diagrammo/dgmo/block.css'),
  'utf8'
);

// Transform 1: `[data-theme="dark"]` → `body.theme-dark`.
// Literal-string replace (not regex) since the bracket characters would need
// escaping; the substring is unique in block.css.
//
// Transform 2: drop `:has()` from the block-frame selectors. dgmo's block.css
// frames the block purely in CSS via `.dgmo:has(> .dgmo-source-wrap[open])`,
// which every zero-JS embed surface relies on. Obsidian's scorecard scan flags
// `:has` (perf lint), and this plugin already runs JS (frameSourcePanel in
// render.ts) that mirrors the panel state onto `.dgmo-has-source` /
// `.dgmo-source-open`. So rewrite the two frame selectors to those classes here
// — obsidian-only, leaving dgmo's shared `:has` intact for other surfaces.
// [open] variant first so its longer selector isn't shadowed by the base one.
const adapted = block
  .split('[data-theme="dark"]')
  .join('body.theme-dark')
  .split('.dgmo:has(> .dgmo-source-wrap[open])')
  .join('.dgmo.dgmo-source-open')
  .split('.dgmo:has(> .dgmo-source-wrap)')
  .join('.dgmo.dgmo-has-source');

const banner = `/* styles.css — GENERATED by scripts/build-styles.mjs. Do not edit directly.
 * Sources: src/styles.css (plugin styles) + @diagrammo/dgmo/block.css
 * (standard embed block, BL-114) with [data-theme="dark"] selectors
 * rewritten to body.theme-dark for Obsidian. */

`;

writeFileSync(join(root, 'styles.css'), banner + plugin + '\n' + adapted);
console.log('[build-styles] wrote styles.css');
