/**
 * Full example markdown note showcasing every dgmo chart type.
 * Generated by the "Create example note" command.
 */
export const EXAMPLE_NOTE = `# Diagrammo Chart Examples

> Every \`\`\`dgmo\`\` code fence below renders a different chart type.
> Edit the data to experiment! For the full editor experience visit [diagrammo.app](https://diagrammo.app).

---

## Bar Chart

\`\`\`dgmo
chart: bar
title: Monthly Revenue by Product Line
xlabel: Product
ylabel: Revenue ($K)

Enterprise: 245
Professional: 182
Starter: 97
Free Trial: 43
Add-ons: 61
Consulting: 128
\`\`\`

---

## Line Chart

\`\`\`dgmo
chart: line
title: Daily Active Users (Q1)
xlabel: Week
ylabel: Users (thousands)

Week 1: 12.4
Week 2: 13.1
Week 3: 14.8
Week 4: 13.9
Week 5: 16.2
Week 6: 17.5
Week 7: 18.1
Week 8: 19.3
Week 9: 21.0
Week 10: 22.4
Week 11: 24.1
Week 12: 23.8
\`\`\`

---

## Multi-Line Chart

\`\`\`dgmo
chart: multi-line
title: Quarterly Revenue vs Operating Cost
xlabel: Quarter
ylabel: Amount ($M)

series: Revenue (blue), Operating Cost (red), Net Profit (green)
Q1 2023: 4.2, 3.1, 1.1
Q2 2023: 4.8, 3.3, 1.5
Q3 2023: 5.1, 3.5, 1.6
Q4 2023: 5.9, 3.7, 2.2
Q1 2024: 6.3, 3.9, 2.4
Q2 2024: 7.1, 4.2, 2.9
\`\`\`

---

## Area Chart

\`\`\`dgmo
chart: area
title: Memory Usage Over Time
xlabel: Hour
ylabel: GB

12am: 2.1
3am: 1.8
6am: 2.4
9am: 5.7
10am: 6.3
12pm: 7.1
2pm: 6.8
4pm: 5.9
6pm: 4.2
9pm: 3.1
11pm: 2.5
\`\`\`

---

## Pie Chart

\`\`\`dgmo
chart: pie
title: Browser Market Share

Chrome: 63.5
Safari: 19.8
Firefox: 6.2
Edge: 5.1
Samsung Internet: 2.8
Opera: 1.4
Other: 1.2
\`\`\`

---

## Doughnut Chart

\`\`\`dgmo
chart: doughnut
title: Cloud Spending by Service

Compute (blue): 34
Storage (cyan): 22
Database (green): 18
Networking (orange): 12
AI/ML (purple): 8
Other (gray): 6
\`\`\`

---

## Radar Chart

\`\`\`dgmo
chart: radar
title: Engineering Team Skills

Frontend: 85
Backend: 72
DevOps: 68
Testing: 90
Documentation: 55
Architecture: 78
\`\`\`

---

## Polar Area Chart

\`\`\`dgmo
chart: polar-area
title: Incident Categories (Last 30 Days)

Security: 12
Performance: 28
Availability: 8
Data Loss: 3
Configuration: 19
Network: 15
\`\`\`

---

## Stacked Bar Chart

\`\`\`dgmo
chart: bar-stacked
title: Support Tickets by Priority
xlabel: Month
ylabel: Tickets

series: Critical (red), High (orange), Medium (yellow), Low (green)
January: 8, 24, 45, 62
February: 12, 19, 51, 58
March: 6, 22, 38, 71
April: 10, 28, 42, 65
May: 5, 15, 48, 70
\`\`\`

---

## Sequence Diagram

\`\`\`dgmo
chart: sequence
title: API Request Flow

User is an actor
App is a frontend
API is a gateway
DB is a database

User -> App: click submit
App -> API: POST /data <- 201 Created
API -> DB: INSERT record <- ok
API -> App: response
App -> User: show confirmation
\`\`\`

---

## Slope Chart

\`\`\`dgmo
chart: slope
title: Programming Language Popularity

2020, 2022, 2025
Python (blue): 3, 1, 1
JavaScript (yellow): 1, 2, 2
TypeScript (cyan): 7, 4, 3
Rust (orange): 18, 12, 5
Go (green): 10, 8, 7
\`\`\`

---

## Word Cloud

\`\`\`dgmo
chart: wordcloud
title: Tech Conference Topics

Kubernetes: 95
Machine Learning: 88
Microservices: 72
DevOps: 68
Serverless: 55
GraphQL: 48
TypeScript: 82
Rust: 62
WebAssembly: 45
Edge Computing: 38
Observability: 52
Platform Engineering: 60
AI Agents: 90
LLM: 85
\`\`\`

---

## Arc Diagram

\`\`\`dgmo
chart: arc
title: Microservice Dependencies
order: group

## Frontend
WebApp -> API Gateway: 5
MobileApp -> API Gateway: 3

## Core Services
API Gateway -> AuthService: 4
API Gateway -> UserService: 5
API Gateway -> OrderService: 3
UserService -> Database: 4
OrderService -> Database: 3
OrderService -> PaymentService: 2

## External
PaymentService -> Stripe: 2
AuthService -> OAuth: 3
\`\`\`

---

## Timeline

\`\`\`dgmo
chart: timeline
title: Product Roadmap

era 2024-01 -> 2024-06: Phase 1 - Foundation
era 2024-07 -> 2024-12: Phase 2 - Growth

marker 2024-03: Beta Launch
marker 2024-09: GA Release

## Engineering
2024-01->2024-03: Core API Development
2024-02->2024-05: Auth & Permissions
2024-04->2024-07: Real-time Features
2024-08->2024-11: Performance Optimization

## Design
2024-01->2024-02: Design System v1
2024-03->2024-05: User Research
2024-06->2024-08: Design System v2
\`\`\`

---

## Venn Diagram

\`\`\`dgmo
chart: venn
title: Full-Stack Developer Skills

Frontend (blue): 120
Backend (green): 95
DevOps (orange): 60
Frontend & Backend: 45
Backend & DevOps: 25
Frontend & DevOps: 15
Frontend & Backend & DevOps: 10
\`\`\`

---

## Quadrant Chart

\`\`\`dgmo
chart: quadrant
title: Feature Prioritization Matrix

x-axis: Low Effort, High Effort
y-axis: Low Impact, High Impact

top-left: Quick Wins
top-right: Major Projects
bottom-left: Fill-ins
bottom-right: Avoid

Dark Mode (blue): 0.25, 0.85
API v2 (red): 0.8, 0.9
Fix Typos: 0.1, 0.15
SSO Integration: 0.75, 0.7
Export CSV: 0.3, 0.6
Mobile App: 0.9, 0.95
\`\`\`
`;
